### PR TITLE
Add support for new devices and fixes J7008

### PR DESCRIPTION
**Pull request by zqm64**
Device list:
j3ltectc - J3109
j3xproltechn - J3110
j3xproltectc - J3119
j5xltecmcc - J5108
j7ltechn - J7008

### CODE REVIEW

**Comment by SebaUbuntu** [comment]
Need some cleanups for defconfigs

**Comment by zqm64** [comment]
Notes:
It's hard to find a solution for camera, It's better to keep it untouched.
J7008 **must** use it's own S6D7AA0X62_BV050HDM panel driver and the overlay dtsi, else the display will be messed up, and even not boots.
CONFIG_INPUT_EVBUG It prints all of touch events to the dmesg.

**Comment by zqm64** [comment]
It's needed to revert this commit 
https://github.com/samsung-msm8916-dev/android_kernel_samsung_msm8916/pull/2/commits/26a56f099b62db2e5fa9cead625aaa8cb6b27e2a
if camera_v2 codes are not compiling.

**Comment by zqm64** [comment]
Note: J3 uses the S5K4H5YC Camera Module.
CONFIG_S5K4H5YC=y
But i didn't see that when i try compile it. Needed to fix.

**Pull request closed without merging**
